# Generated by Django 4.1.1 on 2022-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления коммента')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('text', models.TextField(max_length=200, verbose_name='Содержимое комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Подзаголовок')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления поста')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('short_text', models.TextField(verbose_name='Текст для страницы со статьями')),
                ('full_text', models.TextField(verbose_name='Полный текст поста')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['date_time'],
            },
        ),
    ]
