# Generated by Django 4.1.1 on 2022-11-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Содержимое обращения')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('WCH', 'Обращение рассмотрено'), ('UNW', 'Обращение нерассмотрено')], default='UNW', max_length=3, verbose_name='Статус обращения')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-date_time'],
            },
        ),
    ]
