# Generated by Django 4.1.1 on 2022-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_supportmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='paberu.tocador@gmail.com', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='paberu.tocador@gmail.com', max_length=100, verbose_name='E-mail'),
        ),
    ]
