# Generated by Django 4.1.1 on 2022-11-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_email_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(default='Имя не указано', max_length=100, verbose_name='Клиент'),
        ),
    ]
