# Generated by Django 4.1.1 on 2022-11-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_customer_alter_order_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_order'], 'permissions': (('can_set_status', 'Возможность настройки статуса заказа'),), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
